version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: peak_stock_db
    environment:
      POSTGRES_USER: peak
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: peak_stocks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: peak_stock_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
